config/routes.rb
SbmmnCom::Application.routes.draw do

  get "message/index"

  root :to => "home#index"
  get "home/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "switch/:id/:token" => "sessions#switch", :as => "switch"

  root :to => "home#index"
  resources :users
  resources :sessions do
    get "reset", on: :member
  end
  resources :articles

  resources :password_resets

  namespace :admin do
    root :to => "welcome#index"
    get "welcome/index"
    resources :users
  end

  namespace :office do
    root :to => "welcome#index"
    get "welcome/index"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SbmmnCom</title>
  <!--[if lt IE 9]>
    <%= javascript_include_tag "html5shiv" %>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">

    <header id="main" >

        <% if sponsor %>
          <section id="sponsor_info">
            <p>Name: <%= sponsor.nick.try :capitalize %></p>
            <p>E-mail: <%= sponsor.email1.try :downcase %></p>
            <p>Site: <%= link_to root_url(subdomain: sponsor.subdomain), root_url(subdomain: sponsor.subdomain) %></p>
            <p>Visits this site: <%= sponsor.visit_counter.try :count %></p>
            <p>Visits networking: <%= VisitCounter.total %></p>
          </section>
        <% end %>

      <section id="auth_area">
        <%= link_to "Home", root_path %> |
        <%= link_to "Articles", articles_path %> |
        <% if current_user %>
          Logged in as <%= current_user.email1 %>.
          <%= link_to "Log Out", logout_path %>
        <% else %>
          <%= link_to "Sign Up", signup_path %> or
          <%= link_to "Log In", login_path %>
        <% end %>
      </section>

    </header>

    <section id="main">

      <section id="message">
        <% flash.each do |key, msg| %>
          <%= content_tag :div, msg, :id => key %>
        <% end %>
      </section>


      <section id="content">
        <%= yield %>
      </section>
    </section>






    <footer id="main">

      <nav id="site">
        <header>
          <h1>Site Links</h1>
        </header>
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Articles", articles_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Log In", login_path %></li>
          <li><%= link_to "Log Out", logout_path %></li>
        </ul>
      </nav>

      <nav id="office">
        <header>
          <h1>Office Links</h1>
        </header>
        <ul>
          <li><%= link_to "Home", office_root_path %></li>
        </ul>
      </nav>

      <nav id="admin">
        <header>
          <h1>Admin Links</h1>
        </header>
        <ul>
          <li><%= link_to "Home", admin_root_path %></li>
          <li><%= link_to "Users", admin_users_path %></li>
        </ul>
      </nav>


    </footer>

  </div>

<div id="debug">
  <%= debug sponsor if Rails.env=="development" %>
  <hr/>
  <%= debug session if Rails.env=="development" %>
  <hr/>
  <%= debug flash if Rails.env=="development" %>
  <hr/>
  <%= debug cookies if Rails.env=="development" %>
  <hr/>
  <%= @timer %>
</div>

</body>
</html>